"""The Elasticsearch index template and ILM policy, as data.

Generated from ``infra/elasticsearch/*.json`` — that copy is for operators
applying them with ``curl`` or ``bootstrap.py``; this one is for
``ElasticsearchShipper``, so a ``pip install`` is self-contained and nobody has
to fetch a file out of the repository to get a correct mapping.

The two are checked against each other by ``tests/unit/test_templates.py``. If
they drift, that test fails — rather than a cluster silently getting the wrong
mapping.

``dynamic: false`` is the load-bearing property. Without it Elasticsearch
invents a field for every distinct body shape and the mapping grows until it
refuses writes: measured, 10 000 documents produce 51 fields with it and 20 194
without. Do not edit this file to "allow" a new field.
"""

from __future__ import annotations

import json
from typing import Any

__all__ = [
    "INDEX_TEMPLATE",
    "ILM_POLICY",
    "DATASET_PLACEHOLDER",
    "index_template_for",
    "index_template_name_for",
    "ilm_policy_name_for",
    "DEFAULT_RETENTION_DAYS",
]

#: The token standing in for the dataset in :data:`INDEX_TEMPLATE` and in
#: ``infra/elasticsearch/template-apiaudit.json``. Both carry the *unbound*
#: template; :func:`index_template_for` binds it to one dataset.
#:
#: The template is per dataset, not per package. It has ``priority: 500``,
#: which outranks Elasticsearch's built-in ``logs`` template (100), so a
#: pattern any wider than the dataset's own indices would impose this
#: package's ``dynamic: false`` mapping on unrelated ``logs-*-*`` data
#: streams and strip every field from their documents.
DATASET_PLACEHOLDER = "{dataset}"


def index_template_name_for(dataset: str) -> str:
    """``logs-<dataset>`` — the name this template is installed under."""
    return f"logs-{dataset}"


def ilm_policy_name_for(dataset: str) -> str:
    """``<dataset>-ilm`` — the policy name this template's indices reference."""
    return f"{dataset}-ilm"


def index_template_for(dataset: str) -> dict[str, Any]:
    """:data:`INDEX_TEMPLATE` bound to one dataset, as a fresh dict.

    Substitutes :data:`DATASET_PLACEHOLDER` in ``index_patterns``, in the
    lifecycle policy name and in ``_meta``. A deep copy, so a caller that
    edits the result — the shipper rewrites the ILM phases — cannot corrupt
    the module-level constant for the next caller.
    """
    bound = json.loads(json.dumps(INDEX_TEMPLATE).replace(DATASET_PLACEHOLDER, dataset))
    return dict(bound)

#: The one retention knob. ``None`` means **never delete**, which is the
#: shipped default and why :data:`ILM_POLICY` carries no ``delete`` phase.
#: ``AuditConfig.retention_days`` overrides it; the shipper adds a delete
#: phase back when it is a number.
DEFAULT_RETENTION_DAYS: int | None = None

INDEX_TEMPLATE: dict[str, Any] = {   'index_patterns': ['logs-{dataset}-*'],
    'priority': 500,
    'data_stream': {'hidden': False, 'allow_custom_routing': False},
    'composed_of': [],
    '_meta': {   'package': 'audit_logging',
                 'owner': 'A5 — infrastructure',
                 'schema': 'docs/schema.md (frozen, Phase 0 exit)',
                 'description': 'API request audit documents. Monolithic on purpose: '
                                'composed_of is empty so that no built-in or '
                                'operator-supplied component template (logs@settings, '
                                'logs@mappings, *@custom) can merge in a dynamic:true '
                                'mapping. Everything this data stream is mapped by is '
                                'in this one file.',
                 'field_budget': '45 leaf fields per docs/schema.md §3, plus object '
                                 "containers and 'labels'; total_fields.limit is 200 "
                                 '(AC-10)',
                 'ilm_policy': '{dataset}-ilm',
                 'managed_by': 'infra/elasticsearch/bootstrap.py'},
    'template': {   'settings': {   'index': {   'codec': 'best_compression',
                                                 'number_of_shards': 1,
                                                 'number_of_replicas': 1,
                                                 'refresh_interval': '10s',
                                                 'lifecycle': {'name': '{dataset}-ilm'},
                                                 'mapping': {   'total_fields': {   'limit': 200},
                                                                'ignore_malformed': True,
                                                                'depth': {'limit': 20}},
                                                 'query': {   'default_field': [   'audit.route',
                                                                                   'url.path',
                                                                                   'error.message']}}},
                    'mappings': {   '_meta': {   'schema_version': '1.0.0',
                                                 'source': 'docs/schema.md §2'},
                                    '_source': {'enabled': True},
                                    'dynamic': False,
                                    'date_detection': False,
                                    'numeric_detection': False,
                                    'properties': {   '@timestamp': {   'type': 'date',
                                                                        'format': 'strict_date_optional_time_nanos||strict_date_optional_time||epoch_millis',
                                                                        'ignore_malformed': False},
                                                      'data_stream': {   'dynamic': False,
                                                                         'properties': {   'type': {   'type': 'constant_keyword',
                                                                                                       'value': 'logs'},
                                                                                           'dataset': {   'type': 'constant_keyword'},
                                                                                           'namespace': {   'type': 'constant_keyword'}}},
                                                      'event': {   'dynamic': False,
                                                                   'properties': {   'kind': {   'type': 'constant_keyword',
                                                                                                 'value': 'event'},
                                                                                     'category': {   'type': 'keyword',
                                                                                                     'ignore_above': 256},
                                                                                     'type': {   'type': 'keyword',
                                                                                                 'ignore_above': 256},
                                                                                     'action': {   'type': 'keyword',
                                                                                                   'ignore_above': 256},
                                                                                     'duration': {   'type': 'long',
                                                                                                     'meta': {   'unit': 'nanos'}},
                                                                                     'outcome': {   'type': 'keyword',
                                                                                                    'ignore_above': 32}}},
                                                      'trace': {   'dynamic': False,
                                                                   'properties': {   'id': {   'type': 'keyword',
                                                                                               'ignore_above': 256}}},
                                                      'service': {   'dynamic': False,
                                                                     'properties': {   'name': {   'type': 'keyword',
                                                                                                   'ignore_above': 256},
                                                                                       'version': {   'type': 'keyword',
                                                                                                      'ignore_above': 256},
                                                                                       'environment': {   'type': 'keyword',
                                                                                                          'ignore_above': 256}}},
                                                      'host': {   'dynamic': False,
                                                                  'properties': {   'hostname': {   'type': 'keyword',
                                                                                                    'ignore_above': 256}}},
                                                      'process': {   'dynamic': False,
                                                                     'properties': {   'pid': {   'type': 'long'}}},
                                                      'client': {   'dynamic': False,
                                                                    'properties': {   'ip': {   'type': 'ip'},
                                                                                      'port': {   'type': 'long'}}},
                                                      'user_agent': {   'dynamic': False,
                                                                        'properties': {   'original': {   'type': 'keyword',
                                                                                                          'ignore_above': 1024}}},
                                                      'url': {   'dynamic': False,
                                                                 'properties': {   'path': {   'type': 'keyword',
                                                                                               'ignore_above': 2048},
                                                                                   'query': {   'type': 'keyword',
                                                                                                'ignore_above': 4096}}},
                                                      'http': {   'dynamic': False,
                                                                  'properties': {   'version': {   'type': 'keyword',
                                                                                                   'ignore_above': 16},
                                                                                    'request': {   'dynamic': False,
                                                                                                   'properties': {   'method': {   'type': 'keyword',
                                                                                                                                   'ignore_above': 32},
                                                                                                                     'bytes': {   'type': 'long'},
                                                                                                                     'mime_type': {   'type': 'keyword',
                                                                                                                                      'ignore_above': 256}}},
                                                                                    'response': {   'dynamic': False,
                                                                                                    'properties': {   'status_code': {   'type': 'long'},
                                                                                                                      'bytes': {   'type': 'long'}}}}},
                                                      'user': {   'dynamic': False,
                                                                  'properties': {   'id': {   'type': 'keyword',
                                                                                              'ignore_above': 256},
                                                                                    'name': {   'type': 'keyword',
                                                                                                'ignore_above': 256},
                                                                                    'roles': {   'type': 'keyword',
                                                                                                 'ignore_above': 256}}},
                                                      'error': {   'dynamic': False,
                                                                   'properties': {   'type': {   'type': 'keyword',
                                                                                                 'ignore_above': 256},
                                                                                     'message': {   'type': 'text',
                                                                                                    'norms': False}}},
                                                      'audit': {   'dynamic': False,
                                                                   'properties': {   'route': {   'type': 'keyword',
                                                                                                  'ignore_above': 1024},
                                                                                     'path_params': {   'type': 'flattened',
                                                                                                        'depth_limit': 25,
                                                                                                        'ignore_above': 1024},
                                                                                     'request': {   'dynamic': False,
                                                                                                    'properties': {   'headers': {   'type': 'flattened',
                                                                                                                                     'depth_limit': 25,
                                                                                                                                     'ignore_above': 1024},
                                                                                                                      'query': {   'type': 'flattened',
                                                                                                                                   'depth_limit': 25,
                                                                                                                                   'ignore_above': 1024},
                                                                                                                      'body': {   'type': 'flattened',
                                                                                                                                  'depth_limit': 25,
                                                                                                                                  'ignore_above': 1024},
                                                                                                                      'body_raw': {   'type': 'keyword',
                                                                                                                                      'index': False,
                                                                                                                                      'doc_values': False},
                                                                                                                      'body_bytes': {   'type': 'long'},
                                                                                                                      'body_truncated': {   'type': 'boolean'},
                                                                                                                      'body_parse_failed': {   'type': 'boolean'},
                                                                                                                      'body_skipped': {   'type': 'keyword',
                                                                                                                                          'ignore_above': 32},
                                                                                                                      'multipart': {   'type': 'flattened',
                                                                                                                                       'depth_limit': 25,
                                                                                                                                       'ignore_above': 1024},
                                                                                                                      'query_skipped': {   'type': 'keyword',
                                                                                                                                           'ignore_above': 32}}},
                                                                                     'response': {   'dynamic': False,
                                                                                                     'properties': {   'headers': {   'type': 'flattened',
                                                                                                                                      'depth_limit': 25,
                                                                                                                                      'ignore_above': 1024}}}}},
                                                      'labels': {   'dynamic': False,
                                                                    'properties': {   }}}}}}

ILM_POLICY: dict[str, Any] = {   'policy': {   '_meta': {   'package': 'audit_logging',
                               'managed_by': 'infra/elasticsearch/bootstrap.py'},
                  'phases': {   'hot': {   'min_age': '0ms',
                                           'actions': {   'rollover': {   'max_primary_shard_size': '50gb',
                                                                          'max_age': '7d'},
                                                          'set_priority': {   'priority': 100}}},
                                'warm': {   'min_age': '7d',
                                            'actions': {   'set_priority': {   'priority': 50},
                                                           'allocate': {   'number_of_replicas': 1},
                                                           'forcemerge': {   'max_num_segments': 1},
                                                           'readonly': {}}},
                                'cold': {   'min_age': '14d',
                                            'actions': {   'set_priority': {   'priority': 0},
                                                           'allocate': {   'number_of_replicas': 0}}},
                                }}}
